### ISSUE TITLE
Not working on latest mattermost version

### ISSUE THREAD

**Issue by uhlhosting** [manland/mattermost-plugin-analytics#30]
Unable to find /analytics command.

**Comment by manland** [comment]
Hi @uhlhosting have you think to configure it ? No `/analytics` command means the plugin haven't start. And he biggest fail at start is a bad configuration. 

Can you share some logs of the mattermost server ?

@jasonblais @hanzei do you know a way to help a user with a plugin pb ? I have read a ticket about reporting error directly in console admin, but I don't reminder where and what the state of this feature !?

**Comment by uhlhosting** [comment]
<img width="771" alt="image" src="https://user-images.githubusercontent.com/6324047/56323282-a9392400-616b-11e9-9bc9-cf9cceb97f10.png">
Here is my config

And it seems after making latest upgrade to MM 5.10 and running the new config again it works just fine. The only thing I changed was to give the username/boo in our case a quick permission check and made sure is a team admin.

Still there are some small maybe debug errors I will share here:

https://gist.githubusercontent.com/uhlhosting/3c5e095043e7ab6fb67389e084c91a79/raw/218f95243b833e3c9e7badef571e93d44d238910/mm.log

**Comment by jasonblais** [comment]
@manland If the plugin fails to start, we provide a generic error message in the UI but output additional details in the server logs

![image](https://user-images.githubusercontent.com/13119842/56330802-b51aeb00-6157-11e9-956f-d40832d8f9d0.png)

**Comment by manland** [comment]
Ok @uhlhosting if all is ok it's good :D 

Thanks for sharing logs, I can see when the plugin has started it has failed to retreive user informations. But I don't know why... I need to add some logs for the next user :D

@jasonblais thanks for the quick answer. I think I need to do the same job for this plugin as I made in gitlab-plugin : move all logs from mlog to p.API.ErrorLog to have a better view on what happens where.

Thanks guys I keep the issue open to think to add some logs ;)

Have a nice day

**Comment by uhlhosting** [comment]
@manland can we figure a way to solve the ip addressing issue? While i've looked upon the error logs there were several files reported as missing from 127.0.0.1 the thing is we are using a different setup and out mattermost runs on an internal ip, from where is proxied to nginx. Is there a way maybe this can read the right configured ip from config.json and make sure the files hit the right status.

**Comment by manland** [comment]
@uhlhosting the url of mattermost is taken from system console -> web server -> SiteURL

If you set the good external url of you rmattermost instance, all should be ok.

**Comment by uhlhosting** [comment]
@manland i have nowhere used 127.0.0.1, thats the issue... So there must be some issue while the ip i use is one internal from class 172.x.x.x

**Comment by manland** [comment]
@uhlhosting oups meaculpa I have found [this](https://github.com/manland/mattermost-plugin-analytics/blob/master/server/post.go#L51) and @hanzei have already foud this bug in [#28](https://github.com/manland/mattermost-plugin-analytics/pull/28#discussion_r267365647) but like i'm on [mattermost-plugin-gitlab](https://github.com/manland/mattermost-plugin-gitlab) I haven't finish the PR :man_facepalming: :sweat: sorry

I have a long week-end (public holiday in france) I hope I will found the time to finish this PR in the next 3 days ;)

Thanks to have found this bug! I close this PR when I have push a new version with the fix.

**Comment by manland** [comment]
And voila https://github.com/manland/mattermost-plugin-analytics/releases/tag/v0.2.0 please fill free to reopen this issue or create another if you have anymore problems :rocket:
